# Generated by Django 5.2.16 on 2026-09-15 16:05

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('image', models.ImageField(default='movie/images/default.jpg', upload_to='movie/images/')),
                ('url', models.URLField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=250)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('emb', models.BinaryField(default=movie.models.get_default_array)),
            ],
        ),
    ]
